server:
    port: 8002

api:
    moexservice:
        url: moex:8003/api
        getStocks: /bonds
        getPrices: /prices
    tinkoffservice:
        url: tinkoff:8004/api
        getStocks: /stocks
        getPrices: /prices

spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/tinkoff
        username: tinkoff
        password: tinkoff
