version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tinkoff"
      POSTGRES_USER: "tinkoff"
      POSTGRES_PASSWORD: "tinkoff"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"