create table if not exists users (
    id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(255),
    password varchar(255)
);

create table if not exists roles (
    id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255)
);

create table if not exists roles_users (
    role_id bigint references roles(id),
    user_id bigint references users(id),
    PRIMARY KEY(role_id, user_id)
);

insert into users (user_name, password) values
                                               ('admin', 'admin'),
                                               ('user', 'user');

insert into roles (name) values
                                            ('ROLE_ADMIN'),
                                            ('ROLE_USER');

insert into roles_users (role_id, user_id) values
                                            (1, 1),
                                            (2, 2);